### ISSUE TITLE
serversmasher not working

### ISSUE THREAD

**Issue by AtomicGaming666** [DeadBread76/Raid-Toolbox#124]
hey the server smasher just dont work for me it just sits on loging in and crashes i also get this error when trying to download that FFMPG think or what ever its called

Window will be a boring gray. Try adding call to change_look_and_feel('Dark Blue 3') before your layout definition
 If you seriously want this gray window and no more nagging, add  change_look_and_feel('DefaultNoMoreNagging')

C:\Users\ashfl\Desktop\.HACK AND RAT TOOLS\Raid-Toolbox-master OLD>python RTB.py
Window will be a boring gray. Try adding call to change_look_and_feel('Dark Blue 3') before your layout definition
 If you seriously want this gray window and no more nagging, add  change_look_and_feel('DefaultNoMoreNagging')
Window will be a boring gray. Try adding call to change_look_and_feel('Dark Blue 3') before your layout definition
 If you seriously want this gray window and no more nagging, add  change_look_and_feel('DefaultNoMoreNagging')
Window will be a boring gray. Try adding call to change_look_and_feel('Dark Blue 3') before your layout definition
 If you seriously want this gray window and no more nagging, add  change_look_and_feel('DefaultNoMoreNagging')
Traceback (most recent call last):
  File "C:\Users\ashfl\AppData\Roaming\Python\Python37\site-packages\urllib3\connection.py", line 160, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "C:\Users\ashfl\AppData\Roaming\Python\Python37\site-packages\urllib3\util\connection.py", line 61, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "C:\Users\ashfl\AppData\Local\Programs\Python\Python37\lib\socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ashfl\AppData\Roaming\Python\Python37\site-packages\urllib3\connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "C:\Users\ashfl\AppData\Roaming\Python\Python37\site-packages\urllib3\connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "C:\Users\ashfl\AppData\Roaming\Python\Python37\site-packages\urllib3\connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "C:\Users\ashfl\AppData\Roaming\Python\Python37\site-packages\urllib3\connection.py", line 309, in connect
    conn = self._new_conn()
  File "C:\Users\ashfl\AppData\Roaming\Python\Python37\site-packages\urllib3\connection.py", line 172, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000001593FC2F240>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ashfl\AppData\Roaming\Python\Python37\site-packages\requests\adapters.py", line 449, in send
    timeout=timeout
  File "C:\Users\ashfl\AppData\Roaming\Python\Python37\site-packages\urllib3\connectionpool.py", line 727, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "C:\Users\ashfl\AppData\Roaming\Python\Python37\site-packages\urllib3\util\retry.py", line 439, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='ffmpeg.zeranoe.com', port=443): Max retries exceeded with url: /builds/win64/static/ffmpeg-4.1.3-win64-static.zip (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001593FC2F240>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "RTB.py", line 1018, in <module>
    ff = download_file("https://ffmpeg.zeranoe.com/builds/win64/static/ffmpeg-4.1.3-win64-static.zip")
  File "RTB.py", line 829, in download_file
    with requests.get(url, stream=True) as r:
  File "C:\Users\ashfl\AppData\Roaming\Python\Python37\site-packages\requests\api.py", line 76, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\ashfl\AppData\Roaming\Python\Python37\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\ashfl\AppData\Roaming\Python\Python37\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\ashfl\AppData\Roaming\Python\Python37\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\ashfl\AppData\Roaming\Python\Python37\site-packages\requests\adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='ffmpeg.zeranoe.com', port=443): Max retries exceeded with url: /builds/win64/static/ffmpeg-4.1.3-win64-static.zip (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001593FC2F240>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))

**Comment by AtomicGaming666** [comment]
HELP

![image](https://user-images.githubusercontent.com/39306849/95187869-6794b100-0817-11eb-8581-195957cfed7f.png)
