### ISSUE TITLE
Don't know how to control on termux.

### ISSUE THREAD

**Issue by kapzy** [DeadBread76/Raid-Toolbox#125]
I did everything for the termux way for Android and it worked but I can't figure out how to control it what are the commands and everything please help it would be very appreciated.

**Comment by lilcsz** [comment]
screenshot pls

**Comment by kapzy** [comment]
https://ibb.co/QrNbKfx don't know what to do now what do I type or did I do something wrong?

**Comment by lilcsz** [comment]
@kapzy Use this config file:

https://anonfiles.com/x4a0S0gcp4/config_json

**Comment by lilcsz** [comment]
and your screen will like this
![image](https://user-images.githubusercontent.com/43272857/96378746-c7377880-1196-11eb-976c-85898dea472e.png)

**Comment by kapzy** [comment]
What do I do with the config file

**Comment by kapzy** [comment]
Also I'm on stock termux with no gui so mine will probably look different to yours

**Comment by kapzy** [comment]
@lilcsz will this work with no gui version? Also what to do with the file

**Comment by lilcsz** [comment]
Yes will work. Delete old config file and move my config file.

**Comment by kapzy** [comment]
@lilcsz I did it now what I repeated the steps and same thing what do I do when it says "Click enter to exit"?

**Comment by lilcsz** [comment]
@kapzy Use this app https://play.google.com/store/apps/details?id=ru.iiec.pydroid3&hl=en_US&gl=US

**Comment by lilcsz** [comment]
@kapzy Open RTB.py and run but don't run with terminal

**Comment by kapzy** [comment]
It says no module named RTBFiles even when they are in the same folder and have it

**Comment by Hidden-R3d** [comment]
Run it like this: `python3 RTB.PY nogui`

**Comment by kapzy** [comment]
/storage/emulated/0/Raid-Toolbox $ python3 $ $ RTB.py nogui
Traceback (most recent call last):
  File "RTB.py", line 511, in <module>
    import RTBFiles.attack_dict
ModuleNotFoundError: No module named 'RTBFiles'
/storage/emulated/0/Raid-Toolbox $

Idk how to fix this error

**Comment by lilcsz** [comment]
@DeadBread76

**Comment by Mattlau04** [comment]
@DeadBread76

**Comment by emirbyte** [comment]
@kapzy run the app in the directiory of Raid-Toolbox

**Comment by kapzy** [comment]
@emirbyte please explain wdym

**Comment by lilcsz** [comment]
> @kapzy run the app in the directiory of Raid-Toolbox

he already running on Raid-Toolbox 
ModuleNotFoundError: No module named 'RTBFiles'
/storage/emulated/0/Raid-Toolbox $

**Comment by xAvatar6969** [comment]
> /storage/emulated/0/Raid-Toolbox $ python3 $ RTB.py nogui
> Traceback (most recent call last):
> File "RTB.py", line 511, in
> import RTBFiles.attack_dict
> ModuleNotFoundError: No module named 'RTBFiles'
> /storage/emulated/0/Raid-Toolbox $
> 
> Idk how to fix this error

firts the command is `python3 RTB.py no_gui`
