### ISSUE TITLE
Mass Mentioner and Role Mass Mentioner not working.

### ISSUE THREAD

**Issue by Nitrocosm** [DeadBread76/Raid-Toolbox#55]
When trying to launch an attack using phone-verified tokens, this error code comes up in the error.log file next to every token:

`Error: Missing Access (Code 50001)`

Have tried giving admin access to users but to no avail.

**Comment by joysticks** [comment]
having the same issue.

**Comment by hidden-r4d** [comment]
Running `requests.get("https://canary.discordapp.com/api/v6/guilds/795911539990331432/members?limit=1000")` gives `Error: Missing Access (Code 50001)`, even with a valid (user) token. It is possible to fetch all users in a guild using a bot with the Server Members Intent (using the http request). I will try and see if it is possible using the discord.py library instead of http requests to get a list of member IDs in a server.

**Comment by hidden-r4d** [comment]
I tried editing 
```
...
while True:
            try:
                src = request.get(f"https://canary.discordapp.com/api/v6/guilds/{server}/members?limit=1000",headers=headers, proxies=proxies, timeout=10)
 ...

for member in memberjson:
            memberlist.append(f"<@{member['user']['id']}>")
```

to 

```...
while True:
                try:
                    guild = get_guild(server)

...

 for member in guild.members:
            memberlist.append(f"<@{member.id}>")
```

 but when I run the mass mentioner in RTB, nothing happens and there is nothing in errors.log.

**Comment by hidden-r4d** [comment]
Still nothing. Not really sure what to do now.

**Comment by hidden-r4d** [comment]
I don't think that it's even *possible* to fix this (For the normal mass mentioner at least). See [this](https://stackoverflow.com/questions/63062564/discord-py-self-bot-get-all-user-ids) StackOverflow question.

**Comment by hidden-r4d** [comment]
When testing the mass role mentioner, I found this in errors.log (This might be an unrelated error though)

```
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x000002935E2F63A0>
Traceback (most recent call last):
  File "C:\Users\hidden-r3d\AppData\Local\Programs\Python\Python38\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\hidden-r3d\AppData\Local\Programs\Python\Python38\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\hidden-r3d\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 719, in call_soon
    self._check_closed()
  File "C:\Users\hidden-r3d\AppData\Local\Programs\Python\Python38\lib\asyncio\base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```
