### ISSUE TITLE
Joiner is not working

### ISSUE THREAD

**Issue by BlazeZyrion** [DeadBread76/Raid-Toolbox#95]
As above.
I've tried a lot of vpns, 
i have 2k of tokens that i checked with token checker v1 and v2 also

**Comment by GhazaRiZ** [comment]
Same with me.

please help :(

**Comment by xAvatar6969** [comment]
Strange. Is the invitation valid?

**Comment by BlazeZyrion** [comment]
yes, it is valid

**Comment by Atharv-Agarwal** [comment]
@DeadBread76 RTB joiner still bugged.. Checker v2 says my tokens are verified but it wont work.. Below is the error txt 
```
Window will be a boring gray. Try adding call to change_look_and_feel('Dark Blue 3') before your layout definition
 If you seriously want this gray window and no more nagging, add  change_look_and_feel('DefaultNoMoreNagging') 
Window will be a boring gray. Try adding call to change_look_and_feel('Dark Blue 3') before your layout definition
 If you seriously want this gray window and no more nagging, add  change_look_and_feel('DefaultNoMoreNagging') 
Traceback (most recent call last):
  File "RTBFiles/attack_controller.py", line 552, in <module>
    time.sleep(int(delay))
ValueError: invalid literal for int() with base 10: ''
Token MjczMjA3MjgxMTkyMDA5NzI5... Error: 404: Not Found (Code 0)
Window will be a boring gray. Try adding call to change_look_and_feel('Dark Blue 3') before your layout definition
 If you seriously want this gray window and no more nagging, add  change_look_and_feel('DefaultNoMoreNagging') 
Traceback (most recent call last):
  File "RTBFiles/attack_controller.py", line 552, in <module>
    time.sleep(int(delay))
ValueError: invalid literal for int() with base 10: ''
Token MjczMjA3MjgxMTkyMDA5NzI5... Error: You need to verify your account in order to perform this action. (Code 40002)
Window will be a boring gray. Try adding call to change_look_and_feel('Dark Blue 3') before your layout definition
 If you seriously want this gray window and no more nagging, add  change_look_and_feel('DefaultNoMoreNagging') 
Window will be a boring gray. Try adding call to change_look_and_feel('Dark Blue 3') before your layout definition
 If you seriously want this gray window and no more nagging, add  change_look_and_feel('DefaultNoMoreNagging') 
Token MjczMjA3MjgxMTkyMDA5NzI5... Error: You need to verify your account in order to perform this action. (Code 40002)
Token NjA5NjUwMTQzMTg4MjIxOTYz... Error: You need to verify your account in order to perform this action. (Code 40002)
Token NjA5NjQzMDMxNjQ5MzIwOTYw... Error: You need to verify your account in order to perform this action. (Code 40002)
Token NzE0MTA5NDMwNjkzNjI1ODk2... Error: You need to verify your account in order to perform this action. (Code 40002)
Token NjA5NjUwMTgzODczMjMyOTM4... Error: You need to verify your account in order to perform this action. (Code 40002)
Window will be a boring gray. Try adding call to change_look_and_feel('Dark Blue 3') before your layout definition
 If you seriously want this gray window and no more nagging, add  change_look_and_feel('DefaultNoMoreNagging') 
Window will be a boring gray. Try adding call to change_look_and_feel('Dark Blue 3') before your layout definition
 If you seriously want this gray window and no more nagging, add  change_look_and_feel('DefaultNoMoreNagging') 
```

**Comment by BlazeZyrion** [comment]
> @DeadBread76 RTB joiner still bugged.. Checker v2 says my tokens are verified but it wont work.. Below is the error txt
> 
> ```
> Window will be a boring gray. Try adding call to change_look_and_feel('Dark Blue 3') before your layout definition
>  If you seriously want this gray window and no more nagging, add  change_look_and_feel('DefaultNoMoreNagging') 
> Window will be a boring gray. Try adding call to change_look_and_feel('Dark Blue 3') before your layout definition
>  If you seriously want this gray window and no more nagging, add  change_look_and_feel('DefaultNoMoreNagging') 
> Traceback (most recent call last):
>   File "RTBFiles/attack_controller.py", line 552, in <module>
>     time.sleep(int(delay))
> ValueError: invalid literal for int() with base 10: ''
> Token MjczMjA3MjgxMTkyMDA5NzI5... Error: 404: Not Found (Code 0)
> Window will be a boring gray. Try adding call to change_look_and_feel('Dark Blue 3') before your layout definition
>  If you seriously want this gray window and no more nagging, add  change_look_and_feel('DefaultNoMoreNagging') 
> Traceback (most recent call last):
>   File "RTBFiles/attack_controller.py", line 552, in <module>
>     time.sleep(int(delay))
> ValueError: invalid literal for int() with base 10: ''
> Token MjczMjA3MjgxMTkyMDA5NzI5... Error: You need to verify your account in order to perform this action. (Code 40002)
> Window will be a boring gray. Try adding call to change_look_and_feel('Dark Blue 3') before your layout definition
>  If you seriously want this gray window and no more nagging, add  change_look_and_feel('DefaultNoMoreNagging') 
> Window will be a boring gray. Try adding call to change_look_and_feel('Dark Blue 3') before your layout definition
>  If you seriously want this gray window and no more nagging, add  change_look_and_feel('DefaultNoMoreNagging') 
> Token MjczMjA3MjgxMTkyMDA5NzI5... Error: You need to verify your account in order to perform this action. (Code 40002)
> Token NjA5NjUwMTQzMTg4MjIxOTYz... Error: You need to verify your account in order to perform this action. (Code 40002)
> Token NjA5NjQzMDMxNjQ5MzIwOTYw... Error: You need to verify your account in order to perform this action. (Code 40002)
> Token NzE0MTA5NDMwNjkzNjI1ODk2... Error: You need to verify your account in order to perform this action. (Code 40002)
> Token NjA5NjUwMTgzODczMjMyOTM4... Error: You need to verify your account in order to perform this action. (Code 40002)
> Window will be a boring gray. Try adding call to change_look_and_feel('Dark Blue 3') before your layout definition
>  If you seriously want this gray window and no more nagging, add  change_look_and_feel('DefaultNoMoreNagging') 
> Window will be a boring gray. Try adding call to change_look_and_feel('Dark Blue 3') before your layout definition
>  If you seriously want this gray window and no more nagging, add  change_look_and_feel('DefaultNoMoreNagging') 
> ```

your tokens are not verfied.

topic: for me its still not working

**Comment by Atharv-Agarwal** [comment]
Not to be rude but @BlazeZyrion can you read before replying? I clearly said that checker V2 says that my tokens are *Verified*

**Comment by BlazeZyrion** [comment]
sure
You need to verify your account in order to perform this action. (Code 40002)

Token MjczMjA3MjgxMTkyMDA5NzI5... Error: You need to verify your account in order to perform this action. (Code 40002)
Token NjA5NjUwMTQzMTg4MjIxOTYz... Error: You need to verify your account in order to perform this action. (Code 40002)
Token NjA5NjQzMDMxNjQ5MzIwOTYw... Error: You need to verify your account in order to perform this action. (Code 40002)
Token NzE0MTA5NDMwNjkzNjI1ODk2... Error: You need to verify your account in order to perform this action. (Code 40002)
Token NjA5NjUwMTgzODczMjMyOTM4... Error: You need to verify your account in order to perform this action. (Code 40002)

**Comment by Hidden-R3d** [comment]
@Atharv-Agarwal I'm pretty sure the checker is bugged.

**Comment by hidden-r4d** [comment]
The checker is bugged for sure. Don't trust it.
